package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"github.com/Godric-W/Amadeus/internal/audit"
	"github.com/Godric-W/Amadeus/internal/config"
)

type providerToolStep struct {
	id        string
	name      string
	arguments map[string]any
}

func TestCoreToolsProviderMockE2E(t *testing.T) {
	badPatch := "*** Begin Patch v1\n*** Update File: calc.go\n@@\n-return left * right\n+return left + right\n*** End Patch\n"
	validPatch := "*** Begin Patch v1\n*** Update File: calc.go\n@@\n-func Add(left, right int) int { return left - right }\n+func Add(left, right int) int { return left + right }\n*** Delete File: obsolete.txt\n*** End Patch\n"
	steps := []providerToolStep{
		{id: "read-before", name: "read_file", arguments: map[string]any{"path": "calc.go", "limit": 100}},
		{id: "grep-bug", name: "grep_code", arguments: map[string]any{"query": "return left - right", "path": "."}},
		{id: "patch-conflict", name: "apply_patch", arguments: map[string]any{"patch": badPatch}},
		{id: "read-after-conflict", name: "read_file", arguments: map[string]any{"path": "calc.go"}},
		{id: "patch-valid", name: "apply_patch", arguments: map[string]any{"patch": validPatch}},
		{id: "create-generated", name: "write_file", arguments: map[string]any{"path": "generated.txt", "content": "generated by provider e2e\n", "mode": "create"}},
		{id: "blocked-shell", name: "execute_command", arguments: map[string]any{"command": "rm -rf /"}},
		{id: "test-project", name: "execute_command", arguments: map[string]any{"command": "go test ./...", "timeout_ms": 30000}},
	}

	for _, api := range []config.APIMode{config.APIResponses, config.APIChatCompletions} {
		t.Run(string(api), func(t *testing.T) {
			var mutex sync.Mutex
			var bodies []map[string]any
			server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
				var body map[string]any
				if err := json.NewDecoder(request.Body).Decode(&body); err != nil {
					t.Errorf("decode core tools Provider request: %v", err)
				}
				mutex.Lock()
				bodies = append(bodies, body)
				requestIndex := len(bodies)
				mutex.Unlock()
				writer.Header().Set("Content-Type", "text/event-stream")
				fmt.Fprint(writer, coreToolsProviderFixture(api, requestIndex, steps))
			}))
			defer server.Close()

			amadeusHome := t.TempDir()
			projectDirectory := t.TempDir()
			dialect := config.DialectStandard
			if api == config.APIResponses {
				dialect = config.DialectOpenAI
			}
			writeCommandConfig(t, filepath.Join(amadeusHome, "config.yaml"), fmt.Sprintf(`
default_provider: mock
providers:
  mock:
    api: %s
    dialect: %s
    api_key: core-tools-secret
    base_url: %s/v1
    model: mock-model
    max_retries: 0
agent:
  max_steps: 12
  max_tool_calls: 12
  max_input_tokens: 100000
  max_output_tokens: 10000
  max_duration: 2m
  max_parallel_tools: 2
approval:
  enabled: true
  default: allow
`, api, dialect, server.URL))
			writeE2EFile(t, filepath.Join(projectDirectory, "go.mod"), "module example.com/coretools\n\ngo 1.26.0\n")
			writeE2EFile(t, filepath.Join(projectDirectory, "calc.go"), "package calc\n\nfunc Add(left, right int) int { return left - right }\n")
			writeE2EFile(t, filepath.Join(projectDirectory, "calc_test.go"), "package calc\n\nimport \"testing\"\n\nfunc TestAdd(t *testing.T) { if Add(1, 2) != 3 { t.Fatal(\"unexpected sum\") } }\n")
			writeE2EFile(t, filepath.Join(projectDirectory, "obsolete.txt"), "delete me\n")

			auditSink := audit.NewMemorySink()
			runtime := commandRuntime{
				amadeusRoot: amadeusHome, workingDirectory: projectDirectory, lookupEnv: emptyEnvLookup,
				terminalDetector: func(io.Reader) bool { return false }, agentCommandFactory: defaultAgentCommandFactory,
				auditSinkFactory: func() (audit.Sink, io.Closer, error) { return auditSink, nil, nil },
				runIDFactory:     func() string { return "core-tools-" + string(api) },
				agentContextFactory: func(parent context.Context) (context.Context, context.CancelFunc) {
					return context.WithCancel(parent)
				},
			}
			command := newRootCommandWithRuntime(&configFlags{}, runtime)
			var stdout bytes.Buffer
			var stderr bytes.Buffer
			command.SetIn(strings.NewReader(""))
			command.SetOut(&stdout)
			command.SetErr(&stderr)
			command.SetArgs([]string{"Fix Add, clean obsolete files, create the requested artifact, and run tests"})
			if err := command.Execute(); err != nil {
				t.Fatalf("execute %s core tools Agent: %v\nstderr=%s", api, err, stderr.String())
			}

			mutex.Lock()
			captured := append([]map[string]any(nil), bodies...)
			mutex.Unlock()
			if len(captured) != len(steps)+2 || stdout.String() != "core tools workflow complete\n" {
				t.Fatalf("unexpected %s core tools trace: requests=%d stdout=%q stderr=%q", api, len(captured), stdout.String(), stderr.String())
			}
			assertCoreToolsProviderRequests(t, api, captured)
			assertCoreToolsProject(t, projectDirectory)
			assertCoreToolsAudit(t, auditSink.Snapshot())
			if strings.Contains(stdout.String()+stderr.String(), "core-tools-secret") || !strings.Contains(stderr.String(), "result: completed") {
				t.Fatalf("unsafe or incomplete %s core tools output: stdout=%q stderr=%q", api, stdout.String(), stderr.String())
			}
		})
	}
}

func coreToolsProviderFixture(api config.APIMode, requestIndex int, steps []providerToolStep) string {
	if requestIndex <= len(steps) {
		return providerToolCallFixture(api, requestIndex, steps[requestIndex-1])
	}
	if requestIndex == len(steps)+1 {
		if api == config.APIResponses {
			return responsesTextFixture("core_tools_final", "core tools workflow complete")
		}
		return chatTextFixture("core_tools_final", "core tools workflow complete")
	}
	if api == config.APIResponses {
		return responsesTextFixture("core_tools_reflect", `{"scope":"task","verdict":"accept"}`)
	}
	return chatTextFixture("core_tools_reflect", `{"scope":"task","verdict":"accept"}`)
}

func providerToolCallFixture(api config.APIMode, sequence int, step providerToolStep) string {
	arguments, _ := json.Marshal(step.arguments)
	responseID := fmt.Sprintf("tool_response_%d", sequence)
	itemID := fmt.Sprintf("tool_item_%d", sequence)
	if api == config.APIResponses {
		return strings.Join([]string{
			`event: response.created`, fmt.Sprintf(`data: {"type":"response.created","sequence_number":0,"response":{"id":%q,"status":"in_progress"}}`, responseID), ``,
			`event: response.output_item.added`, fmt.Sprintf(`data: {"type":"response.output_item.added","sequence_number":1,"output_index":0,"item":{"id":%q,"type":"function_call","call_id":%q,"name":%q,"arguments":"","status":"in_progress"}}`, itemID, step.id, step.name), ``,
			`event: response.function_call_arguments.done`, fmt.Sprintf(`data: {"type":"response.function_call_arguments.done","sequence_number":2,"item_id":%q,"output_index":0,"name":%q,"arguments":%q}`, itemID, step.name, string(arguments)), ``,
			`event: response.completed`, fmt.Sprintf(`data: {"type":"response.completed","sequence_number":3,"response":{"id":%q,"status":"completed","usage":{"input_tokens":2,"input_tokens_details":{"cached_tokens":0},"output_tokens":2,"output_tokens_details":{"reasoning_tokens":0},"total_tokens":4}}}`, responseID), ``, `data: [DONE]`, ``,
		}, "\n")
	}
	return strings.Join([]string{
		fmt.Sprintf(`data: {"id":%q,"object":"chat.completion.chunk","created":0,"model":"mock-model","choices":[{"index":0,"delta":{"tool_calls":[{"index":0,"id":%q,"type":"function","function":{"name":%q,"arguments":%q}}]},"finish_reason":null}]}`, responseID, step.id, step.name, string(arguments)), ``,
		fmt.Sprintf(`data: {"id":%q,"object":"chat.completion.chunk","created":0,"model":"mock-model","choices":[{"index":0,"delta":{},"finish_reason":"tool_calls"}]}`, responseID), ``, `data: [DONE]`, ``,
	}, "\n")
}

func chatTextFixture(id, text string) string {
	return strings.Join([]string{
		fmt.Sprintf(`data: {"id":%q,"object":"chat.completion.chunk","created":0,"model":"mock-model","choices":[{"index":0,"delta":{"content":%q},"finish_reason":null}]}`, id, text), ``,
		fmt.Sprintf(`data: {"id":%q,"object":"chat.completion.chunk","created":0,"model":"mock-model","choices":[{"index":0,"delta":{},"finish_reason":"stop"}]}`, id), ``, `data: [DONE]`, ``,
	}, "\n")
}

func assertCoreToolsProviderRequests(t *testing.T, api config.APIMode, captured []map[string]any) {
	t.Helper()
	first, _ := json.Marshal(captured[0])
	for _, fragment := range []string{`"apply_patch"`, `"write_file"`, `"mode"`, `"create"`, `"replace"`} {
		if !bytes.Contains(first, []byte(fragment)) {
			t.Fatalf("%s first request omitted tool contract %s: %s", api, fragment, first)
		}
	}
	checks := []struct {
		request  int
		contains string
	}{
		{request: 2, contains: "return left - right"},
		{request: 3, contains: "calc.go"},
		{request: 4, contains: "patch conflict"},
		{request: 5, contains: "return left - right"},
		{request: 6, contains: "applied 2 patch operation"},
		{request: 7, contains: "generated.txt"},
		{request: 8, contains: "tool execution denied"},
		{request: 9, contains: "example.com/coretools"},
	}
	for _, check := range checks {
		encoded, _ := json.Marshal(captured[check.request-1])
		if !bytes.Contains(encoded, []byte(check.contains)) {
			t.Fatalf("%s request %d omitted %q: %s", api, check.request, check.contains, encoded)
		}
	}
}

func assertCoreToolsProject(t *testing.T, projectDirectory string) {
	t.Helper()
	content, err := os.ReadFile(filepath.Join(projectDirectory, "calc.go"))
	if err != nil || !strings.Contains(string(content), "return left + right") || strings.Contains(string(content), "return left - right") {
		t.Fatalf("valid patch did not update calc.go: content=%q err=%v", content, err)
	}
	generated, err := os.ReadFile(filepath.Join(projectDirectory, "generated.txt"))
	if err != nil || string(generated) != "generated by provider e2e\n" {
		t.Fatalf("write_file create failed: content=%q err=%v", generated, err)
	}
	if _, err := os.Stat(filepath.Join(projectDirectory, "obsolete.txt")); !os.IsNotExist(err) {
		t.Fatalf("patch delete did not remove obsolete.txt: %v", err)
	}
}

func assertCoreToolsAudit(t *testing.T, records []audit.Record) {
	t.Helper()
	if len(records) != 8 {
		t.Fatalf("unexpected core tools audit count: %#v", records)
	}
	blocked := records[6]
	if blocked.ToolName != "execute_command" || blocked.Outcome != audit.OutcomeDeny || blocked.Risk != "blocked" || blocked.ArgumentsSHA256 == "" {
		t.Fatalf("dangerous Shell fallback was not blocked and hashed: %#v", blocked)
	}
	if records[7].ToolName != "execute_command" || records[7].Outcome != audit.OutcomeAllow || records[7].ArgumentsSHA256 == "" {
		t.Fatalf("test command audit is invalid: %#v", records[7])
	}
}
